--- a/src/Makefile
+++ b/src/Makefile
@@ -12,6 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+build_type?=release
 tbb_root?=.
 cfg?=release
 include $(tbb_root)/build/common.inc
@@ -26,29 +27,29 @@ default: tbb tbbmalloc $(if $(use_proxy),tbbproxy)
 all: tbb tbbmalloc tbbproxy test examples
 
 tbb: mkdir
-	$(MAKE) -C "$(work_dir)_release"  -r -f $(tbb_root)/build/Makefile.tbb cfg=release
+	$(MAKE) -C "$(work_dir)_$(build_type)"  -r -f $(tbb_root)/build/Makefile.tbb cfg=$(build_type)
 
 tbbmalloc: mkdir
-	$(MAKE) -C "$(work_dir)_release"  -r -f $(tbb_root)/build/Makefile.tbbmalloc cfg=release malloc
+	$(MAKE) -C "$(work_dir)_$(build_type)"  -r -f $(tbb_root)/build/Makefile.tbbmalloc cfg=$(build_type) malloc
 
 tbbproxy: mkdir
-	$(MAKE) -C "$(work_dir)_release"  -r -f $(tbb_root)/build/Makefile.tbbproxy cfg=release tbbproxy
+	$(MAKE) -C "$(work_dir)_$(build_type)"  -r -f $(tbb_root)/build/Makefile.tbbproxy cfg=$(build_type) tbbproxy
 
 tbbbind: mkdir
-	$(MAKE) -C "$(work_dir)_release"  -r -f $(tbb_root)/build/Makefile.tbbbind cfg=release tbbbind
+	$(MAKE) -C "$(work_dir)_$(build_type)"  -r -f $(tbb_root)/build/Makefile.tbbbind cfg=$(build_type) tbbbind
 
 test: tbb tbbmalloc $(if $(use_proxy),tbbproxy)
-	-$(MAKE) -C "$(work_dir)_release"  -r -f $(tbb_root)/build/Makefile.tbbmalloc cfg=release malloc_test
-	-$(MAKE) -C "$(work_dir)_release"  -r -f $(tbb_root)/build/Makefile.test cfg=release
+	-$(MAKE) -C "$(work_dir)_$(build_type)"  -r -f $(tbb_root)/build/Makefile.tbbmalloc cfg=$(build_type) malloc_test
+	-$(MAKE) -C "$(work_dir)_$(build_type)"  -r -f $(tbb_root)/build/Makefile.test cfg=$(build_type)
 
 rml: mkdir
-	$(MAKE) -C "$(work_dir)_release"  -r -f $(tbb_root)/build/Makefile.rml cfg=release
+	$(MAKE) -C "$(work_dir)_$(build_type)"  -r -f $(tbb_root)/build/Makefile.rml cfg=$(build_type)
 
 examples: tbb tbbmalloc
-	$(MAKE) -C examples -r -f Makefile tbb_root=.. release test
+	$(MAKE) -C examples -r -f Makefile tbb_root=.. $(build_type) test
 
 python: tbb
-	$(MAKE) -C "$(work_dir)_release" -rf $(tbb_root)/python/Makefile install
+	$(MAKE) -C "$(work_dir)_$(build_type)" -rf $(tbb_root)/python/Makefile install
 
 doxygen:
 	doxygen Doxyfile
@@ -56,19 +57,20 @@ doxygen:
 .PHONY: clean clean_examples mkdir info
 
 clean: clean_examples
-	$(shell $(RM) $(work_dir)_release$(SLASH)*.* >$(NUL) 2>$(NUL))
-	$(shell $(RD) $(work_dir)_release >$(NUL) 2>$(NUL))
+	$(shell $(RM) $(work_dir)_$(build_type)$(SLASH)*.* >$(NUL) 2>$(NUL))
+	$(shell $(RD) $(work_dir)_$(build_type) >$(NUL) 2>$(NUL))
 	@echo clean done
 
 clean_examples:
 	$(shell $(MAKE) -s -i -r -C examples -f Makefile tbb_root=.. clean >$(NUL) 2>$(NUL))
 
 mkdir:
-	$(shell $(MD) "$(work_dir)_release" >$(NUL) 2>$(NUL))
-	@echo Created the $(work_dir)_release directory
+	$(shell $(MD) "$(work_dir)_$(build_type)" >$(NUL) 2>$(NUL))
+	@echo Created the $(work_dir)_$(build_type) directory
 
 info:
 	@echo OS: $(tbb_os)
+	@echo build_type=$(build_type)
 	@echo arch=$(arch)
 	@echo compiler=$(compiler)
 	@echo runtime=$(runtime)
